### ISSUE TITLE
ember generate resource broken

### ISSUE THREAD

**Issue by brandonjmckay** [alexspeller/ember-cli-coffees6#5]
Using `ember generate resource <resource name>` doesn't work correctly. It tries to build `.JS` files while the other blueprints use `.COFFEE`.

So I get this error:

```shell
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
installing
  create app/pods/properties/search/model.js
installing
  create tests/unit/pods/properties/search/model-test.js
installing
  create app/pods/properties/search/route.js
  create app/pods/properties/search/template.hbs
ENOENT, no such file or directory '/Users/bmckay/Ember/rew_mobile/app/router.js'
Error: ENOENT, no such file or directory '/Users/bmckay/Ember/rew_mobile/app/router.js'
  at Object.fs.openSync (fs.js:438:18)
  at Object.fs.readFileSync (fs.js:289:15)
  at addRouteToRouter (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/blueprints/route/index.js:106:19)
  at Class.module.exports.afterInstall (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/blueprints/route/index.js:66:7)
  at $$$internal$$tryCatch (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/bmckay/Ember/rew_mobile/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by alexspeller** [comment]
Is this resolved with the latest version on npm?

**Comment by brandonjmckay** [comment]
I actually moved to just the plain `ember-cli-coffeescript` for now. Still trying to migrate to CLI, and haven't been able to fully transfer over yet. Just wanted to let you know in case it was an issue for others as well.

**Comment by alexspeller** [comment]
Hmm OK, thanks!

**Comment by alexspeller** [comment]
this should be fixed now
